package uisi.ru.constructor.model

data class MapStudent(
    val uuid: String,
    val surname: String? = null,
    val name: String? = null,
    val patronymic: String? = null,
    val gender: String? = null,
    val birthday: String? = null,
    val phone: String? = null,
    val regAddr: String? = null,
    val actAddr: String? = null,
    val passportSerial: String? = null,
    val passportNumber: String? = null,
    val passportDate: String? = null,
    val passportSource: String? = null,
    val snils: String? = null,
    val medPolicy: String? = null,
    val foreigner: String? = null,
    val quota: String? = null,
    val enrlDate: String? = null,
    val enrlOrderDate: String? = null,
    val enrlOrderNumber: String? = null,
    val studId: String? = null,
    val studIdDate: String? = null,
    val group: String? = null,
    val educationLevel: String? = null,
    val fundSrc: String? = null,
    val course: String? = null,
    val studyForm: String? = null,
    val program: String? = null,
    val programCode: String? = null,
    val profile: String? = null,
    val duration: String? = null,
    val regEndDate: String? = null,
    val actEndDate: String? = null,
    val orderEndDate: String? = null,
    val orderEndNumber: String? = null,
    val acadStartDate: String? = null,
    val acadEndDate: String? = null,
    val orderAcadDate: String? = null,
    val orderAcadNumber: String? = null,
)
