package uisi.ru.constructor.model

import jakarta.persistence.Column
import java.util.*

data class StudentUpdate(
    val surname: String? = null,
    val name: String? = null,
    val patronymic: String? = null,
    val gender: String? = null,
    val birthday: Date? = null,
    val phone: String? = null,
    val regAddr: String? = null,
    val actAddr: String? = null,
    val passportSerial: String? = null,
    val passportNumber: String? = null,
    val passportDate: Date? = null,
    val passportSource: String? = null,
    val snils: String? = null,
    val medPolicy: String? = null,
    val foreigner: Boolean? = null,
    val quota: Boolean? = null,
    val enrlDate: Date? = null,
    val enrlOrderDate: Date? = null,
    val enrlOrderNumber: String? = null,
    val studId: String? = null,
    val studIdDate: Date? = null,
    val group: String? = null,
    val educationLevel: String? = null,
    val fundSrc: String? = null,
    val course: Short? = null,
    val studyForm: String? = null,
    val program: String? = null,
    val programCode: String? = null,
    val profile: String? = null,
    val duration: Int? = null,
    val regEndDate: Date? = null,
    val actEndDate: Date? = null,
    val orderEndDate: Date? = null,
    val orderEndNumber: String? = null,
    val acadStartDate: Date? = null,
    val acadEndDate: Date? = null,
    val orderAcadDate: Date? = null,
    val orderAcadNumber: String? = null,
)
